version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-api
    container_name: news-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
    environment:
        DB_HOST: db
        DB_DATABASE: news_db
        DB_USERNAME: news_user
        DB_PASSWORD: secret

  webserver:
    image: nginx:alpine
    container_name: news-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - /var/www/vendor # Add this line
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: news-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: news_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
